phase 3 script change.

diff --git a/sam-internal/k8s-out/yul/yul-flowsnake_prod/watchdog-spark-operator.yaml b/sam-internal/k8s-out/yul/yul-flowsnake_prod/watchdog-spark-operator.yaml
--- a/sam-internal/k8s-out/yul/yul-flowsnake_prod/watchdog-spark-operator.yaml
+++ b/sam-internal/k8s-out/yul/yul-flowsnake_prod/watchdog-spark-operator.yaml
@@ -896,10 +896,13 @@ items:
               # || true to avoid failing script if pod has gone away.
               kcfw logs -c madkub-init $1 || true
               log_sub_heading "End $1 madkub-init Log"
-              log_sub_heading "Begin $1 main Log"
-              # || true to avoid failing script if pod has gone away.
-              kcfw logs $1 || true
-              log_sub_heading "End $1 main Log"
+              CONTAINER_NAME=""
+              for CONTAINER_NAME in $(kcfw get $1 -o jsonpath='{.spec.containers[*].name}'); do
+                  log_sub_heading "Begin container $CONTAINER_NAME Log in pod $1"
+                  # || true to avoid failing script if pod has gone away.
+                  kcfw logs -c $CONTAINER_NAME $1 || true
+                  log_sub_heading "End container $CONTAINER_NAME Log"
+              done;
               POD_LOGS_COLLECTED["$1"]="true"
           fi
       }
