Spark Operator Watchdog support for kubectl retries deploy to prd-test.

diff --git a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
--- a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
+++ b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
@@ -46,6 +46,8 @@ items:
       unset KUBECONFIG
 
       NAMESPACE=flowsnake-watchdog
+      KUBECTL_TIMEOUT_SECS=5
+      KUBECTL_ATTEMPTS=3
 
       # Parse command line arguments. https://stackoverflow.com/a/14203146
       POSITIONAL=()
@@ -63,6 +65,18 @@ items:
           --namespace)
           # Use a custom namespace (default is flowsnake-watchdog)
           export NAMESPACE="$2"
+          shift # past argument
+          shift # past value
+          ;;
+          --kubectl-timeout)
+          # Specify timeout (seconds) for individual kubectl invocations (default is 5)
+          export KUBECTL_TIMEOUT_SECS="$2"
+          shift # past argument
+          shift # past value
+          ;;
+          --kubectl-attempts)
+          # Specify number of attempts for individual kubectl invocations (default is 3)
+          export KUBECTL_ATTEMPTS="$2"
           shift # past argument
           shift # past value
           ;;
@@ -95,7 +109,7 @@ items:
       # Exit after 12 minutes to ensure we exit before cliChecker kills us (15 mins) so that all output can be logged.
       TIMEOUT_SECS=$((60*12))
 
-      # output Unix time
+      # output Unix time to stdout
       epoch() {
           date '+%s'
       }
@@ -105,27 +119,56 @@ items:
           sed -e "s/^/$(date +'%m%d %H:%M:%S') [$(epoch)] $APP_NAME - /"
       }
 
-      # Format and output provided string
+      # Format and output provided string to stdout
       log() {
           if [[ "$@" != "" ]]; then
               echo "${@}" | format
           fi
       }
 
-      # Run kubectl in namespace. Prefer kcfw_log when possible
+      # Run kubectl in namespace.
+      # Use for extracting programatic values; otherwise prefer kcfw_log for formatted output.
+      #
+      # stdout is printed without change.
+      # stderr is log-formatted and printed.
+      #
+      # Operations are timed out after KUBECTL_TIMEOUT_SECS and retried KUBECTL_ATTEMPTS times upon timeout or non-zero exit
+      # Timeout and retry events are printed to stderr
       kcfw() {
-        kubectl -n ${NAMESPACE} "$@"
+          ATTEMPT=1
+          while true; do
+              tmpfile=$(mktemp /tmp/$(basename $0)-stderr.XXXXXX)
+              timeout --signal=9 ${KUBECTL_TIMEOUT_SECS} $@ 2>$tmpfile
+              RESULT=$?
+              # Format captured stderr for logging and output it to stderr
+              cat $tmpfile | format >&2
+              rm $tmpfile
+              if [[ $RESULT == 0 ]]; then
+                  # Success! We're done.
+                  return $RESULT;
+              fi;
+              MSG="Invocation ($ATTEMPT/$KUBECTL_ATTEMPTS) of [$@] failed ($(if (( $RESULT == 124 || $RESULT == 137 )); then echo "timed out (${KUBECTL_TIMEOUT_SECS}s)"; else echo $RESULT; fi))."
+              if (( $ATTEMPT <= $KUBECTL_ATTEMPTS )); then
+                  log "$MSG Will sleep $KUBECTL_TIMEOUT_SECS seconds and then try again." >&2
+                  sleep ${KUBECTL_TIMEOUT_SECS}
+              else
+                  log "$MSG Giving up." >&2
+                  return ${RESULT}
+              fi;
+              ATTEMPT=$(($ATTEMPT + 1))
+          done;
       }
 
-      # Run kubectl in namespace, plus prefix output to disambiguate interleaving later
+      # Like kcfw, plus apply log formatting to stdout.
       kcfw_log() {
         # pipefail is set, so sed won't lose any failure exit code returned by kubectl
-        kcfw "$@" 2>&1 | format
+        # stderr is already formatted by kcfw, so only need to add formatting to stdout
+        kcfw "$@" | format
       }
 
       # Extract the "Events" section from a kubectl description of a resource.
       events() {
-          # awk magic prints lines after search term found: https://stackoverflow.com/a/17988834
+          # awk magic prints only lines that occur after the search term is found: https://stackoverflow.com/a/17988834
           kcfw_log describe sparkapplication $APP_NAME | awk '/Events:/{flag=1;next}flag'
       }
 
@@ -172,11 +215,11 @@ items:
 
           # Can't simply copy associative arrays in bash, so perform maintenance on PREVIOUS_POD_REPORTS as we go.
           for POD_NAME in ${REMOVED_POD_NAMES}; do
-              log "Pod ${POD_NAME} removed."
+              log "Pod change detected: ${POD_NAME} removed."
               unset PREVIOUS_POD_REPORTS["$POD_NAME"]
           done
           for POD_NAME in ${NEW_POD_NAMES}; do
-              log "Pod ${POD_NAME}: ${POD_REPORTS["${POD_NAME}"]}.";
+              log "Pod change detected: ${POD_NAME}: ${POD_REPORTS["${POD_NAME}"]}.";
               PREVIOUS_POD_REPORTS["$POD_NAME"]=${POD_REPORTS["${POD_NAME}"]}
           done;
           for POD_NAME in ${EXISTING_POD_NAMES}; do
@@ -186,7 +229,7 @@ items:
               OLD_REPORT="${PREVIOUS_POD_REPORTS[${POD_NAME}]}"
               NEW_REPORT="${POD_REPORTS[${POD_NAME}]}"
               if [[ "${OLD_REPORT}" != "${NEW_REPORT}" ]]; then
-                  log "Pod ${POD_NAME} changed to ${NEW_REPORT%% *} (previously ${OLD_REPORT%% *})."
+                  log "Pod change detected: ${POD_NAME} changed to ${NEW_REPORT%% *} (previously ${OLD_REPORT%% *})."
                   PREVIOUS_POD_REPORTS["$POD_NAME"]="${NEW_REPORT}"
               fi
           done;
@@ -199,14 +242,19 @@ items:
       kcfw_log cluster-info
 
       # ------ Clean up prior runs ---------
-      log "Cleaning up $APP_NAME resources from prior runs"
-      # || true because exit code 1 if spark application can't be found.
-      kcfw_log delete sparkapplication $APP_NAME || true
+      log "Cleaning up $APP_NAME resources from prior runs."
+      # Disable retries and use || true because exit code 1 if spark application can't be found.
+      KUBECTL_ATTEMPTS_BACKUP=${KUBECTL_ATTEMPTS} KUBECTL_ATTEMPTS=1 kcfw_log delete sparkapplication $APP_NAME || true
+      KUBECTL_ATTEMPTS=${KUBECTL_ATTEMPTS_BACKUP}
+
       # kubectl returns success even if no pods match the label selector. But it seems you get an
-      # error if you match a pod and then that pod exits on its own at just the wrong time. So || true here too.
-      kcfw_log delete pod -l $SELECTOR || true
-      # Wait for pods from prior runs to delete.
-      while ! $(kcfw_log get pod -l $SELECTOR | grep "No resources" > /dev/null); do sleep 1; done;
+      # error if you match a pod and then that pod exits on its own at just the wrong time. Retry harmless in that case.
+      # Need || true anyway because grep to filter out the unwanted "No resources found." message will fail if no such message
+      # because there actually was something to delete.
+      kcfw_log delete pod -l $SELECTOR 2>&1 | grep -v "No resources" || true
+
+      # Wait for pods from prior runs to delete by looping until we get No resources result.
+      while ! $(kcfw_log get pod -l $SELECTOR 2>&1 | grep "No resources" > /dev/null); do sleep 1; done;
 
       # ------ Run ---------
       log "Creating SparkApplication $APP_NAME"
@@ -219,12 +267,12 @@ items:
       while ! $(echo ${STATE} | grep -P '(COMPLETED|FAILED)' > /dev/null); do
           EPOCH=$(epoch)
           if (( EPOCH - START_TIME >= TIMEOUT_SECS )); then
-              log "Timeout reached. Aborting wait even though in non-terminal state $STATE."
+              log "Timeout reached. Aborting wait for SparkApplication $APP_NAME even though in non-terminal state $STATE."
               events;
               break
           fi
           if (( EPOCH - LAST_LOGGED > 180 )); then
-              log "...still waiting for terminal state (currently $STATE) after $((EPOCH-START_TIME)) seconds. SparkApplication Events so far:";
+              log "...still waiting for terminal state (currently $STATE) after $((EPOCH-START_TIME)) seconds. SparkApplication $APP_NAME Events so far:";
               events;
               LAST_LOGGED=${EPOCH}
           fi;
