Add impersonation-proxy spark operator watchdog

diff --git a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
--- a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
+++ b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
@@ -39,6 +39,68 @@ items:
     namespace: flowsnake
 - apiVersion: v1
   data:
+    check-spark-operator-v2.sh: |
+      #!/usr/bin/bash
+      set -o nounset
+      set -o errexit
+      set -o pipefail
+
+      # Parse command line arguments. https://stackoverflow.com/a/14203146
+      POSITIONAL=()
+      while [[ $# -gt 0 ]]
+      do
+      key="$1"
+
+      case $key in
+          --impersonation-proxy)
+          IMPERSONATION_PROXY="true"
+          shift
+          ;;
+          *)    # unknown option
+          POSITIONAL+=("$1") # save it in an array for later
+          shift # past argument
+          ;;
+      esac
+      done
+      set -- "${POSITIONAL[@]}" # restore positional parameters
+
+      if [[ -z "$IMPERSONATION_PROXY" ]]; then
+          # Disable use of SAM's custom kubeconfig, restore default Kubernetes behavior (this cluster's kubeapi using service account token)
+          unset KUBECONFIG
+      else
+          # Use a custom kubeconfig to access via MadDog PKI certs and Impersonation Proxy
+          export KUBECONFIG=/watchdog-spark-operator/kubeconfig-impersonation-proxy
+      fi
+
+      kcfw() {
+        kubectl -n flowsnake-watchdog "$@"
+      }
+
+      SPEC=$1
+      APP_NAME=${SPEC%.*}
+      SELECTOR="sparkoperator.k8s.io/app-name=$APP_NAME"
+
+      echo "Cleaning up $APP_NAME resources from prior runs"
+      # || true because exit code 1 if spark application can't be found.
+      kcfw delete sparkapplication $APP_NAME || true
+      # kubectl returns success even if no pods match the label selector. This is helpful,
+      # this will have the side-effect of aborting the script early if it cannot access kubeapi.
+      kcfw delete pod -l $SELECTOR
+      # Wait for pods from prior runs to delete.
+      while ! $(kcfw get pod -l $SELECTOR 2>&1 | grep "No resources" > /dev/null); do sleep 1; done;
+
+      echo "Creating SparkApplication $APP_NAME"
+      kcfw create -f /watchdog-spark-specs/$SPEC
+
+      echo "Waiting for SparkApplication $APP_NAME to complete"
+      # Terminal values are COMPLETED and FAILED https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/design.md#the-crd-controller
+      while ! $(kcfw get sparkapplication $APP_NAME -o jsonpath='{.status.applicationState.state}' | grep -P '(COMPLETED|FAILED)' > /dev/null); do sleep 1; done;
+      echo ---- Begin Spark Driver Log ----
+      kcfw logs $(kcfw get pod -l $SELECTOR -o name)
+      echo ---- End Spark Driver Log ----
+      echo "Terminal SparkApplication $APP_NAME state is $(kcfw get sparkapplication $APP_NAME -o jsonpath='{.status.applicationState.state}')"
+      # Test successful iff final state is COMPLETED. Use exit code from grep.
+      kcfw get sparkapplication $APP_NAME -o jsonpath='{.status.applicationState.state}' | grep COMPLETED > /dev/null
     check-spark-operator.sh: |
       #!/usr/bin/bash
       set -o nounset
@@ -77,6 +139,26 @@ items:
       echo "Terminal SparkApplication $APP_NAME state is $(kcfw get sparkapplication $APP_NAME -o jsonpath='{.status.applicationState.state}')"
       # Test successful iff final state is COMPLETED. Use exit code from grep.
       kcfw get sparkapplication $APP_NAME -o jsonpath='{.status.applicationState.state}' | grep COMPLETED > /dev/null
+    kubeconfig: |
+      apiVersion: v1
+      clusters:
+      - cluster:
+          certificate-authority: /certs/ca.pem
+          server: https://kubernetes-api-test-flowsnake-prd.slb.sfdc.net
+        name: kubernetes
+      contexts:
+      - context:
+          cluster: kubernetes
+          user: kubernetes
+        name: default-context
+      current-context: default-context
+      kind: Config
+      preferences: {}
+      users:
+      - name: kubernetes
+        user:
+          client-certificate: /certs/client/certificates/client.pem
+          client-key: /certs/client/keys/client-key.pem
   kind: ConfigMap
   metadata:
     name: watchdog-spark-on-k8s-script-configmap
@@ -114,8 +196,8 @@ items:
           - --config=/config/watchdog.json
           - -cliCheckerCommandTarget=SparkOperatorTest
           - --hostsConfigFile=/sfdchosts/hosts.json
-          - -watchdogFrequency=15m
-          - -alertThreshold=45m
+          - -watchdogFrequency=1m
+          - -alertThreshold=1m
           - -cliCheckerTimeout=15m
           image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/hypersam:sam-0002530-db32f9dc
           imagePullPolicy: IfNotPresent
