TIMEOUT_* (new states); CONNECTION_REFUSED analysis

diff --git a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
--- a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
+++ b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
@@ -300,6 +300,7 @@ items:
           'KUBECTL_MAX_TRIES_TIMEOUT': re.compile(r'Invocation \([0-9/]*\) of \[kubectl .*\] failed \(timed out \([0-9]*s\)\). Giving up.'),
           'DRIVER_EVICTED': re.compile(r'NodeControllerEviction.*node-controller.*Marking for deletion Pod .*-driver'),
           'MADKUB_INIT_EMPTY_DIR': re.compile(r'Error: failed to start container "madkub-init": .*kubernetes.io~empty-dir/datacerts'),
+          'CONNECTION_REFUSED': re.compile(r'The connection to the server 10.254.208.1:443 was refused'),
       }
 
       metrics_enabled = False
@@ -345,7 +346,7 @@ items:
       r_driver_context_app_submitted = re.compile(r'(?P<spark_time>[- :0-9]*) INFO.*SparkContext.* - Submitted application')
       r_driver_context_jar_added = re.compile(r'(?P<spark_time>[- :0-9]*) INFO.*SparkContext.* - Added JAR file:')
       r_exec_allocator = re.compile(r'(?P<spark_time>[- :0-9]*) INFO.*ExecutorPodsAllocator.* - Going to request [0-9]* executors from Kubernetes')
-      r_timeout_running = re.compile(r'Timeout reached. Aborting wait for SparkApplication .* even though in non-terminal state RUNNING.')
+      r_timeout = re.compile(r'Timeout reached. Aborting wait for SparkApplication .* even though in non-terminal state (?P<state>\w*)\.')
       #r_ driver_running_event = re.compile(r'SparkDriverRunning\s+([0-9]+)([sm])\s+spark-operator\s+Driver .* is running')
       r_exec_pod_creation_event = re.compile(r'\[(?P<epoch>[0-9]+)\] .* - Pod change detected: .*-exec-[0-9]+: (?P<state>.*) on host.*')
       r_exec_pod_creation_event_pending = re.compile(r'\[(?P<epoch>[0-9]+)\] .* - Pod change detected: .*-exec-[0-9]+: Pending on host.*')
@@ -484,28 +485,32 @@ items:
                   return code
 
           # Check for termination due to timeout.
-          if r_timeout_running.search(output):
-              # TODO: Look at collected metrics for a better sense of what normal values are.
-              # timing -> (max_seconds, classification_if_exceeded)
-              thresholds = {
-                  TIMING_METRIC_NAME_DRIVER_POD_DETECTED: (60, 'TIMEOUT_DRIVER_SLOW_POD_CREATION'),
-                  TIMING_METRIC_NAME_DRIVER_POD_PENDING_DELAY: (60, 'TIMEOUT_DRIVER_SLOW_POD_SCHEDULING'),
-                  TIMING_METRIC_NAME_DRIVER_POD_INITIALIZATION: (60, 'TIMEOUT_DRIVER_SLOW_POD_INIT'),
-                  TIMING_METRIC_NAME_DRIVER_APP_SUBMIT: (60, 'TIMEOUT_DRIVER_SLOW_APP_SUBMIT'),
-                  TIMING_METRIC_NAME_DRIVER_APP_LOAD: (60, 'TIMEOUT_DRIVER_SLOW_APP_LOAD'),
-                  TIMING_METRIC_NAME_EXEC_POD_DETECTED: (30, 'TIMEOUT_EXECUTOR_SLOW_POD_CREATION'),
-                  TIMING_METRIC_NAME_EXEC_POD_PENDING_DELAY: (60, 'TIMEOUT_EXECUTOR_SLOW_POD_SCHEDULING'),
-                  TIMING_METRIC_NAME_EXEC_POD_INITIALIZATION: (30, 'TIMEOUT_EXECUTOR_SLOW_POD_INIT'),
-                  TIMING_METRIC_NAME_EXEC_REGISTRATION: (30, 'TIMEOUT_EXECUTOR_SLOW_REGISTRATION'),
-                  TIMING_METRIC_NAME_JOB_RUNTIME: (30, 'TIMEOUT_SLOW_JOB_RUN'),
-                  TIMING_METRIC_NAME_CLEAN_UP: (30, 'TIMEOUT_SLOW_CLEANUP'),
-              }
-              for metric, seconds in timings.iteritems():
-                  if metric in thresholds:
-                      threshold, classification = thresholds[metric]
-                      if seconds >= threshold:
-                          return classification
-              return "UNRECOGNIZED_TIMEOUT"
+          m_timeout = r_timeout.search(output)
+          if m_timeout:
+              if m_timeout.group('state') == 'RUNNING':
+                  # TODO: Look at collected metrics for a better sense of what normal values are.
+                  # timing -> (max_seconds, classification_if_exceeded)
+                  thresholds = {
+                      TIMING_METRIC_NAME_DRIVER_POD_DETECTED: (60, 'TIMEOUT_DRIVER_SLOW_POD_CREATION'),
+                      TIMING_METRIC_NAME_DRIVER_POD_PENDING_DELAY: (60, 'TIMEOUT_DRIVER_SLOW_POD_SCHEDULING'),
+                      TIMING_METRIC_NAME_DRIVER_POD_INITIALIZATION: (60, 'TIMEOUT_DRIVER_SLOW_POD_INIT'),
+                      TIMING_METRIC_NAME_DRIVER_APP_SUBMIT: (60, 'TIMEOUT_DRIVER_SLOW_APP_SUBMIT'),
+                      TIMING_METRIC_NAME_DRIVER_APP_LOAD: (60, 'TIMEOUT_DRIVER_SLOW_APP_LOAD'),
+                      TIMING_METRIC_NAME_EXEC_POD_DETECTED: (30, 'TIMEOUT_EXECUTOR_SLOW_POD_CREATION'),
+                      TIMING_METRIC_NAME_EXEC_POD_PENDING_DELAY: (60, 'TIMEOUT_EXECUTOR_SLOW_POD_SCHEDULING'),
+                      TIMING_METRIC_NAME_EXEC_POD_INITIALIZATION: (30, 'TIMEOUT_EXECUTOR_SLOW_POD_INIT'),
+                      TIMING_METRIC_NAME_EXEC_REGISTRATION: (30, 'TIMEOUT_EXECUTOR_SLOW_REGISTRATION'),
+                      TIMING_METRIC_NAME_JOB_RUNTIME: (30, 'TIMEOUT_SLOW_JOB_RUN'),
+                      TIMING_METRIC_NAME_CLEAN_UP: (30, 'TIMEOUT_SLOW_CLEANUP'),
+                  }
+                  for metric, seconds in timings.iteritems():
+                      if metric in thresholds:
+                          threshold, classification = thresholds[metric]
+                          if seconds >= threshold:
+                              return classification
+                  return "UNRECOGNIZED_TIMEOUT"
+              else:
+                  return 'TIMEOUT_' + (m_timeout.group('state') or 'WITHOUT_STATE')
           else:
               # Failure was *not* due to a timeout.
               if r_spark_submit_failed.search(output):
@@ -854,11 +859,15 @@ items:
 
       # Output logs for specified pod to stdout
       # Future: Alternatively, generate a Splunk link?
+      declare -A POD_LOGS_COLLECTED # pod name -> "true" if logs for pod were already collected
       pod_log() {
-          log_sub_heading "Begin $1 Log"
-          # || true to avoid failing script if pod has gone away.
-          kcfw logs $1 || true
-          log_sub_heading "End $1 Log"
+          if [[ -z "${POD_LOGS_COLLECTED[$1]}" ]]; then
+              log_sub_heading "Begin $1 Log"
+              # || true to avoid failing script if pod has gone away.
+              kcfw logs $1 || true
+              log_sub_heading "End $1 Log"
+              POD_LOGS_COLLECTED["$1"]="true"
+          fi
       }
 
       # Log changes to pods spawned for SparkApplication
@@ -921,6 +930,10 @@ items:
                   fi
                   log "Pod change detected: ${POD_NAME} changed to ${REPORT_DISPLAY} (previously ${OLD_REPORT%% *})."
                   PREVIOUS_POD_REPORTS["$POD_NAME"]="${NEW_REPORT}"
+                  if [[ "${NEW_REPORT%% *}" == "Completed" ]] || [[ "${NEW_REPORT%% *}" == "Error" ]] || [[ "${NEW_REPORT%% *}" == "Terminating" ]]; then
+                      # Grab the logs now rather than waiting until the end of the script; the pod might be deleted by then.
+                      pod_log ${POD_NAME}
+                  fi
               fi
           done;
       }
