Report pod status changes during spark operator watchdog execution

diff --git a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
--- a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
+++ b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
@@ -166,15 +166,52 @@ items:
       log "Creating SparkApplication $APP_NAME"
       kcfw_log create -f $SPEC
       START_TIME=$(epoch)
-      LAST_LOGGED=$START_TIME
 
       # Terminal values are COMPLETED and FAILED https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/design.md#the-crd-controller
       state() {
           kcfw get sparkapplication $APP_NAME -o jsonpath='{.status.applicationState.state}'
       }
+
+      declare -A PREVIOUS_POD_PHASES # pod name -> pod phase
+      report_pod_changes() {
+          unset POD_PHASES
+          declare -A POD_PHASES # pod name -> pod phase
+          # Fetch pod names and their status for this SparkApplication in format <pod_name>:<pod_status> ...
+          # Relevant pods for our spark application have label metadata.labels.spark-app-selector=$APP_ID
+          for POD_AND_PHASE in $(kcfw get pods -l${SELECTOR} --show-all -o template --template '{{ range .items }}{{ .metadata.name }}{{":"}}{{ .status.phase }}{{" "}}{{ end }}' | xargs -n1); do
+              # crack pod:phase into key,value and add to map
+              POD_PHASES["$(echo ${POD_AND_PHASE} | cut -d: -f1)"]="$(echo ${POD_AND_PHASE} | cut -d: -f2)"
+          done;
+
+          # ${!MY_MAP[@]} yields the keys of the associative array
+          # See https://unix.stackexchange.com/a/104848
+          REMOVED_POD_NAMES=$(comm -23 <(echo ${!PREVIOUS_POD_PHASES[@]} | xargs -n1 | sort) <(echo ${!POD_PHASES[@]} | xargs -n1 | sort))
+          NEW_POD_NAMES=$(comm -13 <(echo ${!PREVIOUS_POD_PHASES[@]} | xargs -n1 | sort) <(echo ${!POD_PHASES[@]} | xargs -n1 | sort))
+          EXISTING_POD_NAMES=$(comm -12 <(echo ${!PREVIOUS_POD_PHASES[@]} | xargs -n1 | sort) <(echo ${!POD_PHASES[@]} | xargs -n1 | sort))
+
+          # Can't simply copy associative arrays in bash, so perform maintenance on PREVIOUS_POD_PHASES as we go.
+          for POD_NAME in ${REMOVED_POD_NAMES}; do
+              log "Pod ${POD_NAME} removed."
+              unset PREVIOUS_POD_PHASES["$POD_NAME"]
+          done
+          for POD_NAME in ${NEW_POD_NAMES}; do
+              log "Pod ${POD_NAME} created: ${POD_PHASES["${POD_NAME}"]}.";
+              PREVIOUS_POD_PHASES["$POD_NAME"]=${POD_PHASES["${POD_NAME}"]}
+          done;
+          for POD_NAME in ${EXISTING_POD_NAMES}; do
+              OLD_STATUS="${PREVIOUS_POD_PHASES[${POD_NAME}]}"
+              NEW_STATUS="${POD_PHASES[${POD_NAME}]}"
+              if [[ "${OLD_STATUS}" != "${NEW_STATUS}" ]]; then
+                  log "Pod ${POD_NAME} phase changed to ${NEW_STATUS} (previously ${OLD_STATUS})."
+                  PREVIOUS_POD_PHASES["$POD_NAME"]="${NEW_STATUS}"]
+              fi
+          done;
+      }
+
+      LAST_LOGGED=$(epoch)
       log "Waiting for SparkApplication $APP_NAME to terminate."
       STATE=$(state)
-      while ! $(echo $STATE | grep -P '(COMPLETED|FAILED)' > /dev/null); do
+      while ! $(echo ${STATE} | grep -P '(COMPLETED|FAILED)' > /dev/null); do
           EPOCH=$(epoch)
           if (( EPOCH - START_TIME >= TIMEOUT_SECS )); then
               log "Timeout reached. Aborting wait even though in non-terminal state $STATE."
@@ -182,13 +219,15 @@ items:
               break
           fi
           if (( EPOCH - LAST_LOGGED > 180 )); then
-              log "...still waiting for terminal state (currently $STATE) after $((EPOCH-START_TIME)) seconds. Events so far:";
+              log "...still waiting for terminal state (currently $STATE) after $((EPOCH-START_TIME)) seconds. SparkApplication Events so far:";
               events;
               LAST_LOGGED=${EPOCH}
           fi;
+          report_pod_changes
           sleep 1;
           STATE=$(state)
       done;
+      report_pod_changes
 
       # ------ Report Results ---------
       END_TIME=$(epoch)
