Error handling fixes

diff --git a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
--- a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
+++ b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
@@ -156,12 +156,25 @@ items:
                   log "Test timeout reached. Aborting attempt to execute [kubectl -n ${NAMESPACE} $@]."
                   return 124
               fi
-              tmpfile=$(mktemp /tmp/$(basename $0)-stderr.XXXXXX)
-              timeout --signal=9 ${KUBECTL_TIMEOUT_SECS} kubectl -n ${NAMESPACE} $@ 2>$tmpfile
+              stdout=$(mktemp /tmp/$(basename $0)-stdout.XXXXXX)
+              stderr=$(mktemp /tmp/$(basename $0)-stderr.XXXXXX)
+              set +o errexit
+              timeout --signal=9 ${KUBECTL_TIMEOUT_SECS} kubectl -n ${NAMESPACE} $@ 2>${stderr} >${stdout}
               RESULT=$?
+              set -o errexit
+              # Hack to simplify scripting: if you try to delete something and get back a NotFound, treat that as a success.
+              if [[ $(echo "$@" | grep -P '\bdelete\b') && $(grep -P '\(NotFound\).* not found' ${stderr}) ]]; then
+                  return 0
+              fi
+              # Hack to simplify scripting: 'No resources found' is never useful.
+              # Goofy: get with a selector says "No resources found." on stderr but delete says "No resources found" on stdout.
+              sed -i '/^No resources found\.\?$/d' ${stdout}
+              sed -i '/^No resources found\.\?$/d' ${stderr}
               # Format captured stderr for logging and output it to stderr
-              cat $tmpfile | format >&2
-              rm $tmpfile
+              cat ${stderr} | format >&2
+              rm ${stderr}
+              cat ${stdout}
+              rm ${stdout}
               if [[ $RESULT == 0 ]]; then
                   # Success! We're done.
                   return $RESULT;
@@ -225,7 +238,7 @@ items:
               POD_NAME=$(echo $POD_REPORT | cut -d' ' -f1)
               REPORT=$(echo $POD_REPORT | cut -d' ' -f1 --complement)
               POD_REPORTS["$POD_NAME"]="${REPORT}"
-          done < <(kcfw get pods -l${SELECTOR} --show-all -o wide --no-headers 2>&1 | grep -v 'No resources' | awk '{print $1, $3, "on host", $7}')
+          done < <(kcfw get pods -l${SELECTOR} --show-all -o wide --no-headers | awk '{print $1, $3, "on host", $7}')
 
           # Note: Initially used process substitution (as in FOO=$(comm <(...) <(...) )here, but that left defunct grandchild
           # processes behind. Switch to temp files instead.
@@ -275,23 +288,17 @@ items:
 
       # ------ Clean up prior runs ---------
       log "Cleaning up $APP_NAME resources from prior runs."
-      # Disable retries and use || true because exit code 1 if spark application can't be found.
-      KUBECTL_ATTEMPTS_BACKUP=${KUBECTL_ATTEMPTS}
-      KUBECTL_ATTEMPTS=1
-      kcfw_log delete sparkapplication $APP_NAME || true
-      KUBECTL_ATTEMPTS=${KUBECTL_ATTEMPTS_BACKUP}
+      kcfw_log delete sparkapplication $APP_NAME
 
       # kubectl returns success even if no pods match the label selector. But it seems you get an
-      # error if you match a pod and then that pod exits on its own at just the wrong time. Retry harmless in that case.
-      # Need || true anyway because grep to filter out the unwanted "No resources found." message will fail if no such message
-      # because there actually was something to delete.
-      kcfw_log delete pod -l $SELECTOR 2>&1 | grep -v "No resources" || true
+      # error if you match a pod and then that pod exits on its own at just the wrong time. Harmless, retry will succeed.
+      kcfw_log delete pod -l $SELECTOR
 
       # Wait for SparkApplication from prior run to delete.
       LAST_LOGGED=$(epoch)
       while true; do
           EPOCH=$(epoch)
-          if ! kcfw get sparkapplication $APP_NAME > /dev/null; then
+          if ! kcfw get sparkapplications 2>&1 | grep -P "^${APP_NAME}\s" > /dev/null; then
               break
           fi
           if (( EPOCH - LAST_LOGGED > 60 )); then
@@ -332,6 +339,9 @@ items:
           # Use start time of script for timeout computation in order to still exit in timely fashion even if setup was slow
           if (( EPOCH - START_TIME >= TIMEOUT_SECS )); then
               log "Timeout reached. Aborting wait for SparkApplication $APP_NAME even though in non-terminal state $STATE."
+              # Fire-and-forget delete so that Kubernetes is in a cleaner state when the next test execution starts
+              kubectl -n ${NAMESPACE} delete sparkapplication $APP_NAME 2>&1 > /dev/null || true
+              kubectl -n ${NAMESPACE} delete pod -l $SELECTOR 2>&1 > /dev/null || true
               break
           fi
           if (( EPOCH - LAST_LOGGED > 60 )); then
