Add capture of madkub-init container logs

diff --git a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
--- a/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
+++ b/sam-internal/k8s-out/prd/prd-data-flowsnake_test/watchdog-spark-operator.yaml
@@ -876,10 +876,14 @@ items:
       pod_log() {
           # Checking for key with set -o nounset active: https://stackoverflow.com/a/13221491
           if [[ -z "${POD_LOGS_COLLECTED[$1]+present}" ]]; then
-              log_sub_heading "Begin $1 Log"
+              log_sub_heading "Begin $1 madkub-init Log"
+              # || true to avoid failing script if pod has gone away.
+              kcfw logs -c madkub-init $1 || true
+              log_sub_heading "End $1 madkub-init Log"
+              log_sub_heading "Begin $1 main Log"
               # || true to avoid failing script if pod has gone away.
               kcfw logs $1 || true
-              log_sub_heading "End $1 Log"
+              log_sub_heading "End $1 main Log"
               POD_LOGS_COLLECTED["$1"]="true"
           fi
       }
