slb-cleanup-unknownpods should be able to clean up unscheduled Terminating pods as well
slb-cleanup-unknownpods was created to ensure that daemonset rolling updates would not get stuck when encountering pods in the Unknown state. Typically pods enter the Unknown state when they are scheduled to a dead node.

Recently, we've seen several incidents where VIPs have failed because the slb-realsvrcfg daemonset rollout was stuck waiting for Terminating pods that were assigned to dead nodes.

This flights a change to the slb-cleanup-unknownpods script allowing it to force-delete pods stuck in the unscheduled Terminating state. Enabled only in prd-sdc for now.

diff --git a/sam-internal/k8s-out/prd/prd-sdc/slb-cleanup-unknownpods-configmap.yaml b/sam-internal/k8s-out/prd/prd-sdc/slb-cleanup-unknownpods-configmap.yaml
--- a/sam-internal/k8s-out/prd/prd-sdc/slb-cleanup-unknownpods-configmap.yaml
+++ b/sam-internal/k8s-out/prd/prd-sdc/slb-cleanup-unknownpods-configmap.yaml
@@ -1,14 +1,42 @@
 apiVersion: v1
 data:
   slb-cleanup-unknownpods.sh: |
-    #!/bin/bash -xe
+    #!/bin/bash
+
+    # This script attempts to delete slb pods stuck in the Terminating or Unknown state. Such pods can negatively
+    # impact rolling updates by causing the whole update to get stuck waiting for the pods to become healthy.
+
+    set -o errexit
+    set -o nounset
+    set -o pipefail
+    set -o verbose
+
     while true
     do
-        unknownpodcount=`kubectl get pods -n sam-system | grep slb | grep Unknown |wc -l`
+        # Get all the SLB pods in the sam-system namespace.
+        slb_pods=$(kubectl get pods -n sam-system -o wide --no-headers | grep slb)
+        # Get the subset of pods in the "Unknown" state. Ignore failures if there are no such pods.
+        unknown_pods=$(echo "$slb_pods" | grep Unknown || true)
+        # Get the subset of pods in the "Terminating" state where no IP address is assigned.
+        # Ignore failures if there are no such pods.
+        unscheduled_terminating_pods=$(echo "$slb_pods" | grep Terminating | grep '<none>' || true)
 
-        if [ $unknownpodcount -gt 0 ]
+        # Delete unknown pods, if any.
+        if [[ ! -z $unknown_pods ]]
         then
-            kubectl get pods -n sam-system | grep slb | grep Unknown | sed 's/ .*//'g | xargs kubectl -n sam-system delete pod --grace-period=0 --force
+            pod_names=$(echo "$unknown_pods" | awk '{ print $1 "\n" }')
+            echo Deleting Unknown SLB pods:
+            echo $pod_names
+            echo $pod_names | xargs kubectl -n sam-system delete pod --grace-period=0 --force
+        fi
+
+        # Delete unscheduled terminating pods, if any.
+        if [[ ! -z $unscheduled_terminating_pods ]]
+        then
+            pod_names=$(echo "$unscheduled_terminating_pods" | awk '{ print $1 "\n" }')
+            echo Deleting unscheduled Terminating SLB pods:
+            echo $pod_names
+            echo $pod_names | xargs kubectl -n sam-system delete pod --grace-period=0 --force
         fi
 
         sleep 600
