Run build.sh

diff --git a/sam-internal/k8s-out/prd/prd-sdc/slb-cleanup-unknownpods-configmap.yaml b/sam-internal/k8s-out/prd/prd-sdc/slb-cleanup-unknownpods-configmap.yaml
--- a/sam-internal/k8s-out/prd/prd-sdc/slb-cleanup-unknownpods-configmap.yaml
+++ b/sam-internal/k8s-out/prd/prd-sdc/slb-cleanup-unknownpods-configmap.yaml
@@ -1,6 +1,6 @@
 apiVersion: v1
 data:
-  slb-cleanup-unknownpods.sh: |
+  slb-cleanup-unknownpods.sh: |-
     #!/bin/bash
 
     # This script attempts to delete slb pods stuck in the Terminating or Unknown state. Such pods can negatively
@@ -9,38 +9,58 @@ data:
     set -o errexit
     set -o nounset
     set -o pipefail
-    set -o verbose
+    set -o xtrace
 
-    while true
-    do
-        # Get all the SLB pods in the sam-system namespace.
-        slb_pods=$(kubectl get pods -n sam-system -o wide --no-headers | grep slb)
-        # Get the subset of pods in the "Unknown" state. Ignore failures if there are no such pods.
-        unknown_pods=$(echo "$slb_pods" | grep Unknown || true)
-        # Get the subset of pods in the "Terminating" state where no IP address is assigned.
-        # Ignore failures if there are no such pods.
-        unscheduled_terminating_pods=$(echo "$slb_pods" | grep Terminating | grep '<none>' || true)
+    # Set the interval at which this script will check for stuck SLB pods.
+    interval_in_seconds=600
 
-        # Delete unknown pods, if any.
-        if [[ ! -z $unknown_pods ]]
-        then
-            pod_names=$(echo "$unknown_pods" | awk '{ print $1 "\n" }')
-            echo Deleting Unknown SLB pods:
-            echo $pod_names
-            echo $pod_names | xargs kubectl -n sam-system delete pod --grace-period=0 --force
-        fi
+    # delete_pods deletes the pods passed as argument $1 (in kubectl get pods --no-headers format).
+    # Argument $2 supplies the type of pod being deleted (for display only).
+    function force_delete_pods() {
+        pod_listing=$1
+        stuck_pod_type=$2
 
-        # Delete unscheduled terminating pods, if any.
-        if [[ ! -z $unscheduled_terminating_pods ]]
-        then
-            pod_names=$(echo "$unscheduled_terminating_pods" | awk '{ print $1 "\n" }')
-            echo Deleting unscheduled Terminating SLB pods:
-            echo $pod_names
-            echo $pod_names | xargs kubectl -n sam-system delete pod --grace-period=0 --force
-        fi
+        pod_names=$(echo "$pod_listing" | awk '{ print $1 "\n" }')
+        echo "Force-deleting $stuck_pod_type SLB pods:"
+        echo "$pod_names"
+        echo "$pod_names" | xargs kubectl -n sam-system delete pod --grace-period=0 --force
+    }
 
-        sleep 600
-    done
+    # delete_stuck_pods_loop is the core worker loop of this script. It periodically gets the listing of slb pods,
+    # checks for any that are stuck, and then force-deletes those pods.
+    function delete_stuck_pods_loop() {
+        while true
+        do
+            # Get all the SLB pods in the sam-system namespace.
+            slb_pods=$(kubectl get pods -n sam-system -o wide --no-headers | grep slb)
+            # Get the subset of pods in the "Unknown" state. Ignore failures if there are no such pods.
+            unknown_pods=$(echo "$slb_pods" | grep Unknown || true)
+            # Get the subset of pods in the "Terminating" state where no IP address is assigned.
+            # Ignore failures if there are no such pods.
+            unscheduled_terminating_pods=$(echo "$slb_pods" | grep Terminating | grep '<none>' || true)
+
+            # Delete unknown pods, if any.
+            if [[ ! -z $unknown_pods ]]
+            then
+                force_delete_pods "$unknown_pods" "Unknown"
+            fi
+
+            # Delete unscheduled terminating pods, if any.
+            if [[ ! -z $unscheduled_terminating_pods ]]
+            then
+                force_delete_pods "$unscheduled_terminating_pods" "unscheduled Terminating"
+            fi
+
+            echo "$(date +'%Y-%m-%d %T') Sleeping for $interval_in_seconds seconds."
+            sleep "$interval_in_seconds"
+        done
+    }
+
+    function main() {
+        delete_stuck_pods_loop
+    }
+
+    main
 kind: ConfigMap
 metadata:
   creationTimestamp: null
