Updated phase 2: combined scripts, changed metric name, moved env var into scripts

diff --git a/sam-internal/k8s-out/frf/frf-flowsnake_prod/kubeapi-monitor.yaml b/sam-internal/k8s-out/frf/frf-flowsnake_prod/kubeapi-monitor.yaml
--- a/sam-internal/k8s-out/frf/frf-flowsnake_prod/kubeapi-monitor.yaml
+++ b/sam-internal/k8s-out/frf/frf-flowsnake_prod/kubeapi-monitor.yaml
@@ -7,46 +7,46 @@ items:
 
       set -x
 
+      REPEAT_PERIOD=30
       TIMEOUT_PERIOD=10
 
-      timeout ${TIMEOUT_PERIOD} curl -s -ik ${KUBE_API_ADDRESS}/version && echo
-      STATUS_API=$?
-
-      if [ ${STATUS_API} -eq 0 ]; then
-          METRIC_VALUE=1
-      else
-          METRIC_VALUE=0
-          # When timed out, exit code is 124
-          echo "Failed to reach to the api server - command exit code ${STATUS_API}"
-      fi
-
-      echo "Publishing the result ${METRIC_RESULT} to the Funnel endpoint..."
-
-      METRICS_PUBLISH_PATH=${FUNNEL_ENDPOINT}${METRICS_URL_PATH}?${METRICS_PUBLISH_KEY}=${METRICS_SCHEMA_FINGERPRINT}
-      METRIC_SERVICE=flowsnake
-      METRIC_SUBSERVICE=kubeapi-monitor
-      METRIC_NAME=${ESTATE}.KubeApiserver.Success
-      METRIC_TIMESTAMP=$(date +%s)
-
-      METRIC='[{"service":"'${METRIC_SERVICE}'","subservice":"'${METRIC_SUBSERVICE}'","tags":{"datacenter":"'${KINGDOM}'","superpod":"none","node":"'${NODE_NAME}'"},"metricName":["'${METRIC_NAME}'"],"metricValue":'${METRIC_VALUE}',"timestamp":'${METRIC_TIMESTAMP}'}]'
-
-      timeout ${TIMEOUT_PERIOD} curl -s -X POST -H Content-Type:application/json ${METRICS_PUBLISH_PATH} -d ${METRIC} && echo
-      STATUS_FUNNEL=$?
-
-      if [ ${STATUS_FUNNEL} -ne 0 ]; then
-          echo "Failed to publish metric to the Funnel endpoint - exit code ${STATUS_FUNNEL}"
-          echo "Quitting with exit code ${STATUS_FUNNEL}..."
-          exit ${STATUS_FUNNEL}
-      fi
-    repeat-check.sh: |
-      #!/bin/bash
-
-      set -x
-
-      REPEAT_PERIOD=30
+      METRICS_URL_PATH=/funnel/v1/publishBatch
+      METRICS_PUBLISH_KEY=avroSchemaFingerprint
+      METRICS_SCHEMA_FINGERPRINT=AVG7NnlcHNdk4t_zn2JBnQ
+      KUBE_API_ADDRESS=https://kubernetes.default.svc.cluster.local
 
       while true; do
-          /kubeapi-monitor-scripts/check-kubeapi.sh &
+          {
+              timeout ${TIMEOUT_PERIOD} curl -s -ik ${KUBE_API_ADDRESS}/version && echo
+              STATUS_API=$?
+
+              if [ ${STATUS_API} -eq 0 ]; then
+                  METRIC_VALUE=1
+              else
+                  METRIC_VALUE=0
+                  # When timed out, exit code is 124
+                  echo "Failed to reach to the api server - command exit code ${STATUS_API}"
+              fi
+
+              echo "Publishing the result ${METRIC_VALUE} to the Funnel endpoint..."
+
+              METRICS_PUBLISH_PATH=${FUNNEL_ENDPOINT}${METRICS_URL_PATH}?${METRICS_PUBLISH_KEY}=${METRICS_SCHEMA_FINGERPRINT}
+              METRIC_SERVICE=flowsnake
+              METRIC_SUBSERVICE=kubeapi-monitor
+              METRIC_NAME=KubeApiAvailabilityTest.Success
+              METRIC_TIMESTAMP=$(date +%s)
+
+              METRIC='[{"service":"'${METRIC_SERVICE}'","subservice":"'${METRIC_SUBSERVICE}'","tags":{"datacenter":"'${KINGDOM}'","superpod":"none","pod":"'${ESTATE}'","host":"'${NODE_NAME}'"},"metricName":["'${METRIC_NAME}'"],"metricValue":'${METRIC_VALUE}',"timestamp":'${METRIC_TIMESTAMP}'}]'
+
+              timeout ${TIMEOUT_PERIOD} curl -s -X POST -H Content-Type:application/json ${METRICS_PUBLISH_PATH} -d ${METRIC} && echo
+              STATUS_FUNNEL=$?
+
+              if [ ${STATUS_FUNNEL} -ne 0 ]; then
+                  echo "Failed to publish metric to the Funnel endpoint - exit code ${STATUS_FUNNEL}"
+                  echo "Quitting with exit code ${STATUS_FUNNEL}..."
+                  exit ${STATUS_FUNNEL}
+              fi
+          } &
           sleep ${REPEAT_PERIOD}
       done
   kind: ConfigMap
@@ -73,18 +73,10 @@ items:
       spec:
         containers:
         - command:
-          - /kubeapi-monitor-scripts/repeat-check.sh
+          - /kubeapi-monitor-scripts/check-kubeapi.sh
           env:
           - name: FUNNEL_ENDPOINT
             value: http://ajna0-funnel1-0-frf.data.sfdc.net:80
-          - name: METRICS_URL_PATH
-            value: /funnel/v1/publishBatch
-          - name: METRICS_PUBLISH_KEY
-            value: avroSchemaFingerprint
-          - name: METRICS_SCHEMA_FINGERPRINT
-            value: AVG7NnlcHNdk4t_zn2JBnQ
-          - name: KUBE_API_ADDRESS
-            value: https://kubernetes.default.svc.cluster.local
           - name: ESTATE
             value: frf-flowsnake_prod
           - name: KINGDOM
