removing eval-pr-1

diff --git a/tnrp/evaluate_pr b/tnrp/evaluate_pr
--- a/tnrp/evaluate_pr
+++ b/tnrp/evaluate_pr
@@ -1,15 +1,10 @@
 #!/bin/bash
+#exit on error
 set -e
-
-REPO_OWNER=sam
-
-/opt/sam/evaluate-pr --repo-owner="$REPO_OWNER" --repo-name="$TNRP_PRODUCT" --pr="$STAGE_PULL_REQUEST_ID" --authorizer="$STAGE_GO_TRIGGER_USER" --debug
-
-
-#Don't exit on error
-set +e
 #Print each command
 set -x
+
+REPO_OWNER=sam
 
 #exitIfMergeCommitFound checks if there are any
 #merge commits introduced by the current branch
@@ -32,9 +27,7 @@ exitIfMergeCommitFound() {
     then
         echo "Merge commits are not allowed in PRs"
         echo "For help removing them see http://stackoverflow.com/questions/21115596/remove-a-merge-commit-keeping-current-changes"
-        #we don't exit 1 if evaluate-pr has passed already
-        exit 0
-        #exit 1
+        exit 1
     fi
 }
 
@@ -44,11 +37,8 @@ exitIfMergeCommitFound
 
 cd /tmp
 rm -rf manifests || true
-git clone git@git.soma.salesforce.com:sam/manifests.git
+time git clone git@git.soma.salesforce.com:sam/manifests.git
 
 cd -
 
 /opt/sam/evaluate-pr-2 -authorizer $STAGE_GO_TRIGGER_USER -orig-dir /tmp/manifests -dir-with-changes $PWD -pr="$STAGE_PULL_REQUEST_ID" -smb /opt/sam/sam-manifest-builder  -debug -repo-name manifests
-
-#we don't exit 1 if evaluate-pr has passed already
-exit 0
