ensure versions can be sourced regardless of where the sourcing script is run from

diff --git a/tnrp/evaluate_pr b/tnrp/evaluate_pr
--- a/tnrp/evaluate_pr
+++ b/tnrp/evaluate_pr
@@ -2,7 +2,27 @@
 #exit on error
 set -e
 
-source tnrp/versions
+# Determine the path of tnrp/versions relative to the directory
+# from which the tnrp/evaluate_pr script was called.
+getSMBPackageName() {
+    SCRIPT_DIR="${BASH_SOURCE%/*}"
+    if [[ ! -d  "${SCRIPT_DIR}" ]]; then
+      echo "${SCRIPT_DIR} is missing or not a directory."
+      exit 1
+    fi
+
+    VERSIONS_SCRIPT="${SCRIPT_DIR}/versions"
+    if [[ ! -f "${VERSIONS_SCRIPT}" ]]; then
+      echo "${VERSIONS_SCRIPT} is missing or not a file."
+      exit 1
+    fi
+
+    source "${VERSIONS_SCRIPT}"
+    if [[ -z "${SMBPACKAGE}" ]]; then
+      echo "SMBPACKAGE variable must be non-empty."
+      exit 1
+    fi
+}
 
 REPO_OWNER=sam
 
@@ -12,10 +32,7 @@ else
    echo "*** EXECUTING IN $FIREFLY ENVIRONMENT"
    SAMBINDIR=/sam
    # This is required for SAM to run json consistency tests for sam-internal files
-   if [[ -z "${SMBPACKAGE}" ]]; then
-     echo "SMBPACKAGE variable must be non-empty."
-     exit 1
-   fi
+   getSMBPackageName
    yum install -y make gcc gcc-c++ "${SMBPACKAGE}"
    echo "Verifying package installed: ${SMBPACKAGE}"
    if ! yum list installed "${SMBPACKAGE}"; then
diff --git a/tnrp/package b/tnrp/package
--- a/tnrp/package
+++ b/tnrp/package
@@ -11,17 +11,32 @@ git version
 git log -n 1
 # End of standard setup
 
-source tnrp/versions
+# The boilerplate debug information at the top of this script
+# ensures we are one directory up from this script's location.
+# Thus, incorporate a more hard-coded approach to specifying
+# the path to the tnrp/versions script compared to
+# the dynamic process for doing so performed by
+# the tnrp/evaluate_pr script.
+getSMBPackageName() {
+    VERSIONS_SCRIPT="./tnrp/versions"
+    if [[ ! -f "${VERSIONS_SCRIPT}" ]]; then
+      echo "${VERSIONS_SCRIPT} is missing or not a file."
+      exit 1
+    fi
+
+    source "${VERSIONS_SCRIPT}"
+    if [[ -z "${SMBPACKAGE}" ]]; then
+      echo "SMBPACKAGE variable must be non-empty."
+      exit 1
+    fi
+}
 
 if [ -z "$FIREFLY" ]; then
    SAMBINDIR=/opt/sam
 else
    echo "*** EXECUTING IN $FIREFLY ENVIRONMENT"
    SAMBINDIR=/sam
-   if [[ -z "${SMBPACKAGE}" ]]; then
-     echo "SMBPACKAGE variable must be non-empty."
-     exit 1
-   fi
+   getSMBPackageName
    yum install -y "${SMBPACKAGE}"
    echo "Verifying package installed: ${SMBPACKAGE}"
    if ! yum list installed "${SMBPACKAGE}"; then
