phase3 promotion: log pod status instead of phase, hostname

diff --git a/sam-internal/k8s-out/iad/iad-flowsnake_prod/watchdog-spark-operator.yaml b/sam-internal/k8s-out/iad/iad-flowsnake_prod/watchdog-spark-operator.yaml
--- a/sam-internal/k8s-out/iad/iad-flowsnake_prod/watchdog-spark-operator.yaml
+++ b/sam-internal/k8s-out/iad/iad-flowsnake_prod/watchdog-spark-operator.yaml
@@ -81,7 +81,7 @@ items:
       # Success of this command demonstrates successful connection via impersonation proxy and mapping to
       # user account flowsnake_test.flowsnake-watchdog (which in turn is bound to flowsnake-client-flowsnake-watchdog-Role)
       # (Success does not depend on whether there exist any sparkapplication resources in the namespace)
-      kubectl -n flowsnake-watchdog get sparkapplications
+      kubectl -n ${2:-flowsnake-watchdog} get sparkapplications
     check-spark-operator.sh: |
       #!/usr/bin/bash
       set -o nounset
@@ -90,6 +90,8 @@ items:
 
       # Disable use of SAM's custom kubeconfig, restore default Kubernetes behavior (this cluster's kubeapi using service account token)
       unset KUBECONFIG
+
+      NAMESPACE=flowsnake-watchdog
 
       # Parse command line arguments. https://stackoverflow.com/a/14203146
       POSITIONAL=()
@@ -104,6 +106,12 @@ items:
           shift # past argument
           shift # past value
           ;;
+          --namespace)
+          # Use a custom namespace (default is flowsnake-watchdog)
+          export NAMESPACE="$2"
+          shift # past argument
+          shift # past value
+          ;;
           *)    # unknown option
           POSITIONAL+=("$1") # save it in an array for later
           shift # past argument
@@ -112,20 +120,38 @@ items:
       done
       set -- "${POSITIONAL[@]}" # restore positional parameters
 
-      SPEC=$1
+      # Check if spec is a jsonnet template
+      if [[ ".jsonnet" == "${1: -8}" ]] ; then
+          jsonnet -V jenkinsId=${TEST_RUNNER_ID} -V dockerTag=${DOCKER_TAG} -V s3ProxyHost=${S3_PROXY_HOST} -V driverServiceAccount=${DRIVER_SERVICE_ACCOUNT} ${1} -m /strata-test-specs-out
+          SPEC_INPUT=$(basename "$1")
+          SPEC_NAME=${SPEC_INPUT%%.*}
+          if [ -f "/strata-test-specs-out/${SPEC_NAME}.json" ]; then
+              SPEC="/strata-test-specs-out/${SPEC_NAME}.json"
+          else
+              echo "spec /strata-test-specs-out/${SPEC_NAME}.json doesnt exist."
+              exit 1
+          fi
+      else
+          # regular spec
+          SPEC=$1
+      fi
+
       APP_NAME=$(python -c 'import json,sys; print json.load(sys.stdin)["metadata"]["name"]' < $SPEC)
       SELECTOR="sparkoperator.k8s.io/app-name=$APP_NAME"
       # Exit after 12 minutes to ensure we exit before cliChecker kills us (15 mins) so that all output can be logged.
       TIMEOUT_SECS=$((60*12))
 
+      # output Unix time
       epoch() {
           date '+%s'
       }
 
+      # Format string for log output by decorating with date, time, app name
       format() {
           sed -e "s/^/$(date +'%m%d %H:%M:%S') [$(epoch)] $APP_NAME - /"
       }
 
+      # Format and output provided string
       log() {
           if [[ "$@" != "" ]]; then
               echo "${@}" | format
@@ -134,7 +160,7 @@ items:
 
       # Run kubectl in namespace. Prefer kcfw_log when possible
       kcfw() {
-        kubectl -n flowsnake-watchdog "$@"
+        kubectl -n ${NAMESPACE} "$@"
       }
 
       # Run kubectl in namespace, plus prefix output to disambiguate interleaving later
@@ -143,16 +169,82 @@ items:
         kcfw "$@" 2>&1 | format
       }
 
+      # Extract the "Events" section from a kubectl description of a resource.
       events() {
           # awk magic prints lines after search term found: https://stackoverflow.com/a/17988834
           kcfw_log describe sparkapplication $APP_NAME | awk '/Events:/{flag=1;next}flag'
       }
 
+      # Return the state of the Spark application.
+      # Terminal values are COMPLETED and FAILED https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/design.md#the-crd-controller
+      state() {
+          kcfw get sparkapplication $APP_NAME -o jsonpath='{.status.applicationState.state}'
+      }
+
+      # Log changes to pods spawned for SparkApplication
+      declare -A PREVIOUS_POD_REPORTS # pod name -> "<pod_status> on host <nodeName>"
+      report_pod_changes() {
+          unset POD_REPORTS
+          declare -A POD_REPORTS # pod name -> "<pod_name> <pod_status> on host <nodeName>"
+          # Fetch pod names and their status for this SparkApplication
+          # Note that the status from kubectl get contains a more informative single-term status than is available in the JSON.
+          # The JSON contains the phase (Pending -> Running -> Completed), which does not mention Init, and the detailed
+          # conditions and containerStatuses lists, which are difficult to summarize.
+          # Relevant pods for our spark application have label metadata.labels.spark-app-selector=$APP_ID
+          # Reading command ouptut line by line: https://unix.stackexchange.com/a/52027
+          while read POD_REPORT; do
+              POD=$(echo $POD_REPORT | cut -d' ' -f1)
+              REPORT=$(echo $POD_REPORT | cut -d' ' -f1 --complement)
+              POD_REPORTS["$POD"]="${REPORT}"
+          done < <(kcfw get pods -l${SELECTOR} --show-all -o wide --no-headers | awk '{print $1, $3, "on host", $7}')
+
+          # Note: Initially used process substitution (as in FOO=$(comm <(...) <(...) )here, but that left defunct grandchild
+          # processes behind. Switch to temp files instead.
+          # (Not totally clear on why. Something like: process substitution never collects the exit status of the invoked
+          # process. Thus when the Bash script exits, the process gets re-parented to the cliChecker. But the cliChecker
+          # does not collect it either, so zombie process entries pile up.)
+          PREVIOUS_POD_NAMES_FILE=$(mktemp /tmp/$(basename $0)-previous-pods.XXXXXX)
+          CURRENT_POD_NAMES_FILE=$(mktemp /tmp/$(basename $0)-current-pods.XXXXXX)
+          # Write out the names of the pods. ${!MY_MAP[@]} yields the keys of the associative array
+          echo ${!PREVIOUS_POD_REPORTS[@]} | xargs -n1 | sort > "$PREVIOUS_POD_NAMES_FILE"
+          echo ${!POD_REPORTS[@]} | xargs -n1 | sort > "$CURRENT_POD_NAMES_FILE"
+          # Compare pod names from before with ones present now.
+          # Bash array set operations: See https://unix.stackexchange.com/a/104848
+          REMOVED_POD_NAMES=$(comm -23 "$PREVIOUS_POD_NAMES_FILE" "$CURRENT_POD_NAMES_FILE")
+          NEW_POD_NAMES=$(comm -13 "$PREVIOUS_POD_NAMES_FILE" "$CURRENT_POD_NAMES_FILE")
+          EXISTING_POD_NAMES=$(comm -12 "$PREVIOUS_POD_NAMES_FILE" "$CURRENT_POD_NAMES_FILE")
+          rm "$PREVIOUS_POD_NAMES_FILE"
+          rm "$CURRENT_POD_NAMES_FILE"
+
+          # Can't simply copy associative arrays in bash, so perform maintenance on PREVIOUS_POD_REPORTS as we go.
+          for POD_NAME in ${REMOVED_POD_NAMES}; do
+              log "Pod ${POD_NAME} removed."
+              unset PREVIOUS_POD_REPORTS["$POD_NAME"]
+          done
+          for POD_NAME in ${NEW_POD_NAMES}; do
+              log "Pod ${POD_NAME}: ${POD_REPORTS["${POD_NAME}"]}.";
+              PREVIOUS_POD_REPORTS["$POD_NAME"]=${POD_REPORTS["${POD_NAME}"]}
+          done;
+          for POD_NAME in ${EXISTING_POD_NAMES}; do
+              # The hostname won't change, so only report the pod status. ${VAR%% *} means delete everything after the first space
+              # space. Thus "<pod_name> <pod_status> on host <nodeName>" becomes "<pod_name>"
+              # http://tldp.org/LDP/abs/html/string-manipulation.html
+              OLD_REPORT="${PREVIOUS_POD_REPORTS[${POD_NAME}]}"
+              NEW_REPORT="${POD_REPORTS[${POD_NAME}]}"
+              if [[ "${OLD_REPORT}" != "${NEW_REPORT}" ]]; then
+                  log "Pod ${POD_NAME} changed to ${NEW_REPORT%% *} (previously ${OLD_REPORT%% *})."
+                  PREVIOUS_POD_REPORTS["$POD_NAME"]="${NEW_REPORT}"
+              fi
+          done;
+      }
+
+
+      # ------ Initialize ---------
       log "Beginning $APP_NAME test"
       # Sanity-check kubeapi connectivity
       kcfw_log cluster-info
 
-      # ------ Clean up ---------
+      # ------ Clean up prior runs ---------
       log "Cleaning up $APP_NAME resources from prior runs"
       # || true because exit code 1 if spark application can't be found.
       kcfw_log delete sparkapplication $APP_NAME || true
@@ -167,27 +259,26 @@ items:
       kcfw_log create -f $SPEC
       START_TIME=$(epoch)
 
+      LAST_LOGGED=$(epoch)
       log "Waiting for SparkApplication $APP_NAME to terminate."
-      # Terminal values are COMPLETED and FAILED https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/design.md#the-crd-controller
-      i=0
-      state() {
-          kcfw get sparkapplication $APP_NAME -o jsonpath='{.status.applicationState.state}'
-      }
       STATE=$(state)
-      while ! $(echo $STATE | grep -P '(COMPLETED|FAILED)' > /dev/null); do
-          if ((i % 180 == 0 & i > 0)); then
-              log "...still waiting for terminal state (currently $STATE) after $i seconds. Events so far:";
-              events;
-          fi;
+      while ! $(echo ${STATE} | grep -P '(COMPLETED|FAILED)' > /dev/null); do
           EPOCH=$(epoch)
           if (( EPOCH - START_TIME >= TIMEOUT_SECS )); then
               log "Timeout reached. Aborting wait even though in non-terminal state $STATE."
+              events;
               break
           fi
-          ((i = i + 1))
+          if (( EPOCH - LAST_LOGGED > 180 )); then
+              log "...still waiting for terminal state (currently $STATE) after $((EPOCH-START_TIME)) seconds. SparkApplication Events so far:";
+              events;
+              LAST_LOGGED=${EPOCH}
+          fi;
+          report_pod_changes
           sleep 1;
           STATE=$(state)
       done;
+      report_pod_changes # Report final status of spawned pods
 
       # ------ Report Results ---------
       END_TIME=$(epoch)
@@ -209,6 +300,26 @@ items:
 
       log "Completion of $APP_NAME test, returning $EXIT_CODE"
       exit $EXIT_CODE
+    kubeconfig-impersonation-proxy: |
+      apiVersion: v1
+      clusters:
+      - cluster:
+          certificate-authority: /certs/ca.pem
+          server: https://kubernetes-api-flowsnake-iad.slb.sfdc.net
+        name: kubernetes
+      contexts:
+      - context:
+          cluster: kubernetes
+          user: kubernetes
+        name: default-context
+      current-context: default-context
+      kind: Config
+      preferences: {}
+      users:
+      - name: kubernetes
+        user:
+          client-certificate: /certs/client/certificates/client.pem
+          client-key: /certs/client/keys/client-key.pem
   kind: ConfigMap
   metadata:
     name: watchdog-spark-on-k8s-script-configmap
@@ -255,10 +366,10 @@ items:
           resources:
             limits:
               cpu: "1"
-              memory: 500Mi
+              memory: 1Gi
             requests:
               cpu: "1"
-              memory: 500Mi
+              memory: 1Gi
           volumeMounts:
           - mountPath: /config
             name: config
